---
- name: check if package exists
  hosts: servera
  become: yes

  tasks: 
    - name: check if httpd config file exists
      stat:
        path: /etc/http/conf.d/httpd.conf
      register: checkconf

    - name: check if file exists
      assert:
        that:
        - not checkconf.stat.exists
