---
- name: use ansible_facts to update motd file
  hosts: web
  become: yes
  tasks:
    - name: get all facts in variable
      debug:
        var: ansible_facts

    - name: write server info managed node to /etc/motd
      template:
        src: templates/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

