---
- name: webserver package installation
  hosts: test
  vars:
     page_title: landing page
     page_description: landing page description
  tasks:
    - name: make entry in /etc/hosts for webserver
      lineinfile:
        path: /etc/hosts
        line: '192.168.56.12 ansible-2 web'
        state: present

    - name: install webserver
      yum:
        name: "{{ packages}}"
        state: latest
      vars:
        packages:
          - httpd

# first method to copy index.html from files to remote host
    - name: copy index.html to /var/www/html directory
      copy:
        src: files/index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: 0644

    - name: first method to check page configured
      uri:
        url: http://ansible-2
        return_content: yes
        status_code: 200

# End of first method of using webserver page && start of second method

    - name: copy index.html.j2 using the template module
      template:
        src: files/index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: first method to check page configured using templates
      uri:
        url: http://ansible-2
        return_content: yes
        status_code: 200

# End of second method creation of templates.

    - name: start and enable webserver service
      service:
          name: httpd
          enabled: true
          state: started

# implementing multiple plays and using mariadb
- name: database server installations
  hosts: test
  tasks:
    - name: install mariadb
      yum:
        name: mariadb-server
        state: latest

    - name: start and enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: true
