---
- name: test example for loop
  hosts: web
  vars:
    runtask: false
    nums:
      - one
      - two
      - three
  gather_facts: no

  tasks:
    - name: looping 
      debug:
        msg: this is "{{ item }}"
      loop: "{{ nums }}"
      when: runtask

    - name: second task
      debug:
        msg: this is from second task of the play

      
