---
- name: create passwordless SSH to Ansible Managed hosts
  hosts: web
  become: yes
  tasks:
    - name: Ensure key in ~/.ssh/authorized_keys
      authorized_key:
        user: root
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub
