---
- name: display banner for motd
  hosts: test
  tasks:
    - name: banner display
      template:
        src: files/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
