---
- name: display message
  hosts: localhost
  tasks:
    - name: print output of ansible_facts
      debug:
        msg: >
          The package to install on {{ ansible_fqdn }} is {{ ansible_facts.ansible_local.custom.packages.web_package }}
